version: "3"
services:
  serverstatus:
    build:
      context: .
      dockerfile: Dockerfile
    image: cppla/serverstatus:latest
    container_name: serverstatus
    restart: unless-stopped
    networks:
      serverstatus-network:
        ipv4_address: 172.23.0.2
    volumes:
      - ./server/config.json:/ServerStatus/server/config.json 
      - ./web/json:/usr/share/nginx/html/json
    ports:
      - 35601:35601
      - 8080:80
  bot:
    build:
      context: ./plugin
      dockerfile: Dockerfile-telegram
    container_name: bot4sss
    restart: unless-stopped
    networks:
      serverstatus-network:
        ipv4_address: 172.23.0.3
    environment:
      - TG_CHAT_ID=tg_chat_id
      - TG_BOT_TOKEN=tg_bot_token

networks:
  serverstatus-network:
    name: serverstatus-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
